// The keyx package defines the protocol buffer messages and services
// used for key exchange operations. This is part of the edgelink
// system, which uses the exchanged keys to setup a wireguard based
// secure tunnel.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: keyx/api/v1/keyx.proto

package keyx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyExchange_ExchangeKeys_FullMethodName = "/keyx.KeyExchange/ExchangeKeys"
)

// KeyExchangeClient is the client API for KeyExchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The KeyExchange service provides an RPC method for exchanging
// public keys between nodes.
type KeyExchangeClient interface {
	// ExchangeKeys is an RPC method that allows a client to send its
	// public key to the server and receive the server's public key in
	// response.
	ExchangeKeys(ctx context.Context, in *PublicKey, opts ...grpc.CallOption) (*PublicKey, error)
}

type keyExchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyExchangeClient(cc grpc.ClientConnInterface) KeyExchangeClient {
	return &keyExchangeClient{cc}
}

func (c *keyExchangeClient) ExchangeKeys(ctx context.Context, in *PublicKey, opts ...grpc.CallOption) (*PublicKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicKey)
	err := c.cc.Invoke(ctx, KeyExchange_ExchangeKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyExchangeServer is the server API for KeyExchange service.
// All implementations must embed UnimplementedKeyExchangeServer
// for forward compatibility.
//
// The KeyExchange service provides an RPC method for exchanging
// public keys between nodes.
type KeyExchangeServer interface {
	// ExchangeKeys is an RPC method that allows a client to send its
	// public key to the server and receive the server's public key in
	// response.
	ExchangeKeys(context.Context, *PublicKey) (*PublicKey, error)
	mustEmbedUnimplementedKeyExchangeServer()
}

// UnimplementedKeyExchangeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyExchangeServer struct{}

func (UnimplementedKeyExchangeServer) ExchangeKeys(context.Context, *PublicKey) (*PublicKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeKeys not implemented")
}
func (UnimplementedKeyExchangeServer) mustEmbedUnimplementedKeyExchangeServer() {}
func (UnimplementedKeyExchangeServer) testEmbeddedByValue()                     {}

// UnsafeKeyExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyExchangeServer will
// result in compilation errors.
type UnsafeKeyExchangeServer interface {
	mustEmbedUnimplementedKeyExchangeServer()
}

func RegisterKeyExchangeServer(s grpc.ServiceRegistrar, srv KeyExchangeServer) {
	// If the following call pancis, it indicates UnimplementedKeyExchangeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyExchange_ServiceDesc, srv)
}

func _KeyExchange_ExchangeKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyExchangeServer).ExchangeKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyExchange_ExchangeKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyExchangeServer).ExchangeKeys(ctx, req.(*PublicKey))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyExchange_ServiceDesc is the grpc.ServiceDesc for KeyExchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyExchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keyx.KeyExchange",
	HandlerType: (*KeyExchangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeKeys",
			Handler:    _KeyExchange_ExchangeKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keyx/api/v1/keyx.proto",
}
