// The keyx package defines the protocol buffer messages and services
// used for key exchange operations. This is part of the edgelink
// system, which uses the exchanged keys to setup a wireguard based
// secure tunnel.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.2
// source: keyx/api/v1/keyx.proto

package keyx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublicKey is a message that contains a single field, 'key', which
// represents a public key in string format. This message is used in
// the ExchangeKeys RPC method to facilitate the exchange of public
// keys between nodes.
type PublicKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// key is a string representation of a public key.
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_keyx_api_v1_keyx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_keyx_api_v1_keyx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_keyx_api_v1_keyx_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_keyx_api_v1_keyx_proto protoreflect.FileDescriptor

var file_keyx_api_v1_keyx_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6b, 0x65, 0x79, 0x78, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x65,
	0x79, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x65, 0x79, 0x78, 0x22, 0x1d,
	0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x32, 0x41, 0x0a,
	0x0b, 0x4b, 0x65, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x0c,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x0f, 0x2e, 0x6b,
	0x65, 0x79, 0x78, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x1a, 0x0f, 0x2e,
	0x6b, 0x65, 0x79, 0x78, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x00,
	0x42, 0x29, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x6f, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x6c, 0x69, 0x6e,
	0x6b, 0x2f, 0x6b, 0x65, 0x79, 0x78, 0x92, 0x03, 0x02, 0x08, 0x02, 0x62, 0x08, 0x65, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
}

var (
	file_keyx_api_v1_keyx_proto_rawDescOnce sync.Once
	file_keyx_api_v1_keyx_proto_rawDescData = file_keyx_api_v1_keyx_proto_rawDesc
)

func file_keyx_api_v1_keyx_proto_rawDescGZIP() []byte {
	file_keyx_api_v1_keyx_proto_rawDescOnce.Do(func() {
		file_keyx_api_v1_keyx_proto_rawDescData = protoimpl.X.CompressGZIP(file_keyx_api_v1_keyx_proto_rawDescData)
	})
	return file_keyx_api_v1_keyx_proto_rawDescData
}

var file_keyx_api_v1_keyx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_keyx_api_v1_keyx_proto_goTypes = []any{
	(*PublicKey)(nil), // 0: keyx.PublicKey
}
var file_keyx_api_v1_keyx_proto_depIdxs = []int32{
	0, // 0: keyx.KeyExchange.ExchangeKeys:input_type -> keyx.PublicKey
	0, // 1: keyx.KeyExchange.ExchangeKeys:output_type -> keyx.PublicKey
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keyx_api_v1_keyx_proto_init() }
func file_keyx_api_v1_keyx_proto_init() {
	if File_keyx_api_v1_keyx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keyx_api_v1_keyx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keyx_api_v1_keyx_proto_goTypes,
		DependencyIndexes: file_keyx_api_v1_keyx_proto_depIdxs,
		MessageInfos:      file_keyx_api_v1_keyx_proto_msgTypes,
	}.Build()
	File_keyx_api_v1_keyx_proto = out.File
	file_keyx_api_v1_keyx_proto_rawDesc = nil
	file_keyx_api_v1_keyx_proto_goTypes = nil
	file_keyx_api_v1_keyx_proto_depIdxs = nil
}
